#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "usage: ./compile <len> <x> <y>"
    exit 1
fi

# compile the program with the X and Y macros
# definied by the function calling this script
spin -a -DLEN=$1 -DX=$2 -DY=$3 tt.pml
gcc -o pan -DSAFETY pan.c
./pan
